### PR TITLE
Fix strip and extend

### LINKED ISSUE #6: remove expand strip
I think this feature is excessive. Better to use native arrays instead of "some language".

### PR DESCRIPTION
**Pull request by TrySound**
fix #6

### CODE REVIEW

**Comment by jonschlinkert** [comment]
@TrySound I added you as a collab, feel free to merge. I tried adding you on npm too, what username should I use? thanks!

**Comment by TrySound** [comment]
@jonschlinkert The same trysound

**Comment by TrySound** [comment]
@jonschlinkert ASAP! Need to fix last release. package.json `files` should contain all used files.

**Comment by TrySound** [comment]
@jonschlinkert But it's buggy in npm. Will move index.js to lib. This is the best way.

**Comment by jonschlinkert** [comment]
fixed. I added `lib/` to `files` in package.json. 

> Will move index.js to lib. This is the best way.

why? I'd prefer to keep index.js in the root but I'll leave that to you

**Comment by TrySound** [comment]
@jonschlinkert Sometimes npm ignores root index.js when publish.
What about npm access? https://www.npmjs.com/~trysound

**Comment by jonschlinkert** [comment]
> What about npm access?

sure, I asked somewhere else in these issues what you're username was. I'll get you added in a moment

**Comment by TrySound** [comment]
@jonschlinkert As I already said. The same `trysound`

**Comment by jonschlinkert** [comment]
sorry I didn't see that. when I tried `trysound` earlier (from direct copy/paste) it didn't work. I'll try again

**Comment by jonschlinkert** [comment]
done

**Comment by TrySound** [comment]
@jonschlinkert Thanks!

**Pull request merged**
